### ISSUE TITLE
update mysql databases on visit webpage

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TC-Unused-Guid-Search-web#3] opened 2016-08-05 23:49 UTC
I am looking to have unused guid searcher self updated when someone visits the page reading the content of a local git repository on that way the searcher can be hosted somewhere without having to use a server to have the database updated.

**Comment by walter-exit** [comment] 2016-09-28 01:11
Duplicate of ticket #666. Closed.

**Comment by walter-exit** [comment] 2016-09-28 01:11
Just kidding mate, I'll help you out.

**Comment by Gacko** [comment] 2017-03-12 17:10
Done in 94da8e571fec380a27fd43a17584b673ef476633.

**Closed as completed by Gacko** 2017-03-12 17:10 UTC
Labels: enhancement
